### PR TITLE
PHP 7 on Travis needs phpunit

### PR DESCRIPTION
**Pull request by szepeviktor**
@znarf

### CODE REVIEW

**Comment by szepeviktor** [comment]
False! Test code need to be changed: https://stackoverflow.com/a/6065766/1606933

**Comment by znarf** [comment]
@szepeviktor Am I correct that it's a challenge to have test run on PHP 5.x and PHP 7.x at the same time?

**Comment by szepeviktor** [comment]
@znarf I would introduce a custom class in the test and say:

```php
if PHP >=7 :
  class custom-class extends new-class {}
else
  class custom-class extends old-class {}
endif
```

**Comment by szepeviktor** [comment]
scrutinizer still needs the phpunit package:

https://scrutinizer-ci.com/g/access-watch/access-watch-php/inspections/76c3ca1b-4aaa-494d-9127-e6e8d127fdad

**Pull request merged**
